services:
  frontend:
    build:
      context: .
      # target 定义了在多阶段 Dockerfile 中定义的要构建的阶段。
      target: dev-envs
    container_name: frontend-dev
    ports:
      - "80:3000"
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
